In [1]:
import torch

print(torch.__version__)

# Check if CUDA is available
if torch.cuda.is_available():
    print("CUDA is available. PyTorch will use the GPU.")
else:
    print("CUDA is not available. PyTorch will use the CPU.")

# Create a tensor
x = torch.rand(5, 3)
print("Random Tensor:\n", x)

2.4.0+cu121
CUDA is not available. PyTorch will use the CPU.
Random Tensor:
 tensor([[2.4947e-02, 3.8126e-02, 6.6221e-05],
        [5.1309e-01, 4.8147e-01, 9.2950e-01],
        [8.9915e-01, 9.2792e-01, 9.2482e-01],
        [2.1973e-01, 9.5797e-01, 9.5079e-01],
        [5.6678e-01, 2.5443e-01, 6.4480e-01]])


In [2]:
#creating tensor 
scaler = torch.tensor(7)
scaler

tensor(7)

In [3]:
scaler.ndim

0

In [4]:
scaler.item()

7

In [5]:
vector = torch.tensor([3,4])
vector

tensor([3, 4])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
TENSOR = torch.tensor([[[1,2,3],
                         [3,6,9],
                         [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [14]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [15]:
rand_tensor = torch.rand(4, 3)
rand_tensor

tensor([[0.1813, 0.2543, 0.0884],
        [0.1491, 0.4187, 0.7827],
        [0.4055, 0.5141, 0.3754],
        [0.7739, 0.0589, 0.8025]])

In [16]:
rand_tensor.ndim

2

In [17]:
rand_img_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels(R,G,B)
rand_img_size_tensor.shape, rand_img_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [18]:
zero = torch.zeros(4,3)
zero

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [19]:
zero*rand_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [20]:
ones = torch.ones(4,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [21]:
#torch.range(0, 10) 
one_to_ten =torch.arange(0, 10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
torch.arange(0, 1000, 100)

tensor([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [23]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
x = torch.arange(11, 21)
x

tensor([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [25]:
x_reshape = x.reshape([5, 2])
x_reshape, x_reshape.shape

(tensor([[11, 12],
         [13, 14],
         [15, 16],
         [17, 18],
         [19, 20]]),
 torch.Size([5, 2]))

In [26]:
z = x.view(2, 5) 
z, z.shape

(tensor([[11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]]),
 torch.Size([2, 5]))

In [27]:
# view of a tensor shares memory with the original tensor
z[:, 0] = 5 
z, x

(tensor([[ 5, 12, 13, 14, 15],
         [ 5, 17, 18, 19, 20]]),
 tensor([ 5, 12, 13, 14, 15,  5, 17, 18, 19, 20]))

In [28]:
x_stacked = torch.stack([x, x, x], dim=0)
x_stacked

tensor([[ 5, 12, 13, 14, 15,  5, 17, 18, 19, 20],
        [ 5, 12, 13, 14, 15,  5, 17, 18, 19, 20],
        [ 5, 12, 13, 14, 15,  5, 17, 18, 19, 20]])

In [29]:
x_stacked = torch.stack([x, x, x], dim=1)
x_stacked

tensor([[ 5,  5,  5],
        [12, 12, 12],
        [13, 13, 13],
        [14, 14, 14],
        [15, 15, 15],
        [ 5,  5,  5],
        [17, 17, 17],
        [18, 18, 18],
        [19, 19, 19],
        [20, 20, 20]])

In [30]:
x_squeezed = x.squeeze()
x_squeezed, x_squeezed.shape

(tensor([ 5, 12, 13, 14, 15,  5, 17, 18, 19, 20]), torch.Size([10]))

In [31]:
x_unsqueezed = x.unsqueeze(dim=0)
x_unsqueezed, x_unsqueezed.shape

(tensor([[ 5, 12, 13, 14, 15,  5, 17, 18, 19, 20]]), torch.Size([1, 10]))

In [32]:
x_unsqueezed = x.unsqueeze(dim=1)
x_unsqueezed, x_unsqueezed.shape

(tensor([[ 5],
         [12],
         [13],
         [14],
         [15],
         [ 5],
         [17],
         [18],
         [19],
         [20]]),
 torch.Size([10, 1]))

In [33]:
rand_img_size_tensor.shape

torch.Size([224, 224, 3])

In [34]:
x_permuted = rand_img_size_tensor.permute(2, 0, 1)
x_permuted.shape

torch.Size([3, 224, 224])

In [35]:
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [36]:
array.dtype

dtype('float64')

In [37]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [38]:
tensor = torch.from_numpy(array).type(torch.float32)
tensor, tensor.dtype

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.float32)

In [39]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [40]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor


(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [41]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [42]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)


tensor([[0.2580, 0.8887, 0.7512, 0.7516],
        [0.3598, 0.8288, 0.2579, 0.2109],
        [0.4030, 0.2056, 0.5912, 0.7951]])
tensor([[0.2023, 0.8712, 0.8444, 0.5507],
        [0.1754, 0.0100, 0.3430, 0.8624],
        [0.9853, 0.6166, 0.6044, 0.5837]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [45]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
