In [1]:
import torch

print(torch.__version__)

# Check if CUDA is available
if torch.cuda.is_available():
    print("CUDA is available. PyTorch will use the GPU.")
else:
    print("CUDA is not available. PyTorch will use the CPU.")

# Create a tensor
x = torch.rand(5, 3)
print("Random Tensor:\n", x)

2.4.0+cu121
CUDA is not available. PyTorch will use the CPU.
Random Tensor:
 tensor([[0.9220, 0.7054, 0.1423],
        [0.9381, 0.4994, 0.8887],
        [0.7051, 0.6416, 0.5417],
        [0.3373, 0.6505, 0.6548],
        [0.3552, 0.5905, 0.7400]])


In [2]:
#creating tensor 
scaler = torch.tensor(7)
scaler

tensor(7)

In [3]:
scaler.ndim

0

In [4]:
scaler.item()

7

In [5]:
vector = torch.tensor([3,4])
vector

tensor([3, 4])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
TENSOR = torch.tensor([[[1,2,3],
                         [3,6,9],
                         [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [14]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [15]:
rand_tensor = torch.rand(4, 3)
rand_tensor

tensor([[0.0921, 0.3285, 0.7528],
        [0.1828, 0.1777, 0.6877],
        [0.2870, 0.7673, 0.7806],
        [0.0188, 0.8742, 0.7560]])

In [16]:
rand_tensor.ndim

2

In [17]:
rand_img_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels(R,G,B)
rand_img_size_tensor.shape, rand_img_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [18]:
zero = torch.zeros(4,3)
zero

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [19]:
zero*rand_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [20]:
ones = torch.ones(4,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [21]:
#torch.range(0, 10) 
one_to_ten =torch.arange(0, 10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
torch.arange(0, 1000, 100)

tensor([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [23]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
x = torch.arange(11, 21)
x

tensor([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [25]:
x_reshape = x.reshape([5, 2])
x_reshape, x_reshape.shape

(tensor([[11, 12],
         [13, 14],
         [15, 16],
         [17, 18],
         [19, 20]]),
 torch.Size([5, 2]))

In [26]:
z = x.view(2, 5) 
z, z.shape

(tensor([[11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]]),
 torch.Size([2, 5]))

In [27]:
# view of a tensor shares memory with the original tensor
z[:, 0] = 5 
z, x

(tensor([[ 5, 12, 13, 14, 15],
         [ 5, 17, 18, 19, 20]]),
 tensor([ 5, 12, 13, 14, 15,  5, 17, 18, 19, 20]))

In [28]:
x_stacked = torch.stack([x, x, x], dim=0)
x_stacked

tensor([[ 5, 12, 13, 14, 15,  5, 17, 18, 19, 20],
        [ 5, 12, 13, 14, 15,  5, 17, 18, 19, 20],
        [ 5, 12, 13, 14, 15,  5, 17, 18, 19, 20]])

In [29]:
x_stacked = torch.stack([x, x, x], dim=1)
x_stacked

tensor([[ 5,  5,  5],
        [12, 12, 12],
        [13, 13, 13],
        [14, 14, 14],
        [15, 15, 15],
        [ 5,  5,  5],
        [17, 17, 17],
        [18, 18, 18],
        [19, 19, 19],
        [20, 20, 20]])

In [30]:
x_squeezed = x.squeeze()
x_squeezed, x_squeezed.shape

(tensor([ 5, 12, 13, 14, 15,  5, 17, 18, 19, 20]), torch.Size([10]))

In [31]:
x_unsqueezed = x.unsqueeze(dim=0)
x_unsqueezed, x_unsqueezed.shape

(tensor([[ 5, 12, 13, 14, 15,  5, 17, 18, 19, 20]]), torch.Size([1, 10]))

In [32]:
x_unsqueezed = x.unsqueeze(dim=1)
x_unsqueezed, x_unsqueezed.shape

(tensor([[ 5],
         [12],
         [13],
         [14],
         [15],
         [ 5],
         [17],
         [18],
         [19],
         [20]]),
 torch.Size([10, 1]))

In [33]:
rand_img_size_tensor.shape

torch.Size([224, 224, 3])

In [34]:
x_permuted = rand_img_size_tensor.permute(2, 0, 1)
x_permuted.shape

torch.Size([3, 224, 224])