In [1]:
import torch

print(torch.__version__)

# Check if CUDA is available
if torch.cuda.is_available():
    print("CUDA is available. PyTorch will use the GPU.")
else:
    print("CUDA is not available. PyTorch will use the CPU.")

# Create a tensor
x = torch.rand(5, 3)
print("Random Tensor:\n", x)

2.4.0+cu121
CUDA is not available. PyTorch will use the CPU.
Random Tensor:
 tensor([[0.8696, 0.7628, 0.6170],
        [0.0447, 0.9269, 0.0326],
        [0.6327, 0.3309, 0.7265],
        [0.5130, 0.5478, 0.6103],
        [0.2245, 0.9012, 0.7733]])


In [4]:
#creating tensor 
scaler = torch.tensor(7)
scaler

tensor(7)

In [5]:
scaler.ndim

0

In [6]:
scaler.item()

7

In [9]:
vector = torch.tensor([3,4])
vector

tensor([3, 4])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [14]:
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [15]:
MATRIX.ndim

2

In [16]:
MATRIX.shape

torch.Size([2, 2])

In [20]:
TENSOR = torch.tensor([[[1,2,3],
                         [3,6,9],
                         [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [18]:
TENSOR.ndim

3

In [19]:
TENSOR.shape

torch.Size([1, 3, 3])

In [21]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [25]:
rand_tensor = torch.rand(4, 3)
rand_tensor

tensor([[0.7364, 0.7183, 0.9310],
        [0.5700, 0.5919, 0.7043],
        [0.7619, 0.0773, 0.6801],
        [0.8181, 0.6770, 0.3717]])

In [26]:
rand_tensor.ndim

2

In [28]:
rand_img_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels(R,G,B)
rand_img_size_tensor.shape, rand_img_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [35]:
zero = torch.zeros(4,3)
zero

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [37]:
zero*rand_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [38]:
ones = torch.ones(4,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [49]:
#torch.range(0, 10) 
one_to_ten =torch.arange(0, 10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
torch.arange(0, 1000, 100)

tensor([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [50]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [53]:
x = torch.arange(11, 21)
x

tensor([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [58]:
x_reshape = x.reshape([5, 2])
x_reshape, x_reshape.shape

(tensor([[11, 12],
         [13, 14],
         [15, 16],
         [17, 18],
         [19, 20]]),
 torch.Size([5, 2]))